apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: github-runner-components
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '60'
spec:
  project: default
  source:
    repoURL: git@github.com:freegitopsmagic-com/gitops.git
    path: registry/clusters/mgmt/components/github-runner
    targetRevision: HEAD
  destination:
    name: in-cluster
    namespace: github-runner
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - Replace=true
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 5m0s
        factor: 2
