---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mgmt-stormforge-agent-components
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '100'
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:freegitopsmagic-com/gitops.git
    path: registry/clusters/mgmt/components/stormforge-agent
    targetRevision: HEAD
  destination:
    name: in-cluster
    namespace: stormforge-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
