apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubernetes-toolkit
  namespace: new
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kubernetes-toolkit
  namespace: new
rules:
  - apiGroups:
      - apps
    resources:
      - deployments
      - statefulsets
    verbs:
      - get
      - watch
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kubernetes-toolkit
  namespace: new
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kubernetes-toolkit
subjects:
  - kind: ServiceAccount
    name: kubernetes-toolkit
    namespace: new
---
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '20'
  name: kubernetes-toolkit-vcluster-api
  namespace: new
spec:
  template:
    spec:
      containers:
        - args:
            - wait-for
            - deployment
            - --namespace
            - new
            - --label
            - app=vcluster-api
          image: public.ecr.aws/kubefirst/kubernetes-toolkit:0.0.8
          imagePullPolicy: IfNotPresent
          name: kubernetes-toolkit
      restartPolicy: OnFailure
      serviceAccountName: kubernetes-toolkit
---
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '20'
  name: kubernetes-toolkit-vcluster-controller
  namespace: new
spec:
  template:
    spec:
      containers:
        - args:
            - wait-for
            - deployment
            - --namespace
            - new
            - --label
            - app=vcluster-controller
          image: public.ecr.aws/kubefirst/kubernetes-toolkit:0.0.8
          imagePullPolicy: IfNotPresent
          name: kubernetes-toolkit
      restartPolicy: OnFailure
      serviceAccountName: kubernetes-toolkit
---
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '20'
  name: kubernetes-toolkit-vcluster
  namespace: new
spec:
  template:
    spec:
      containers:
        - args:
            - wait-for
            - deployment
            - --namespace
            - new
            - --label
            - app=vcluster
          image: public.ecr.aws/kubefirst/kubernetes-toolkit:0.0.8
          imagePullPolicy: IfNotPresent
          name: kubernetes-toolkit
      restartPolicy: OnFailure
      serviceAccountName: kubernetes-toolkit
---
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '20'
  name: kubernetes-toolkit-vcluster-etcd
  namespace: new
spec:
  template:
    spec:
      containers:
        - args:
            - wait-for
            - statefulset
            - --namespace
            - new
            - --label
            - app=vcluster-etcd
          image: public.ecr.aws/kubefirst/kubernetes-toolkit:0.0.8
          imagePullPolicy: IfNotPresent
          name: kubernetes-toolkit
      restartPolicy: OnFailure
      serviceAccountName: kubernetes-toolkit
