---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mgmt-stormforge-agent
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: '3'
spec:
  destination:
    namespace: stormforge-system
    name: in-cluster
  project: default
  source:
    chart: stormforge-agent
    repoURL: registry.stormforge.io/library
    targetRevision: 2.10.8
    helm:
      releaseName: stormforge
      values: |
        clusterName: mgmt
        stormforge:
          address: https://api.stormforge.io/
        manageAuthSecret: false
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
